# This is an example GitHub Actions workflow that will allow you to build your project with every push or pull request.
# For more information, see:
# https://docs.github.com/actions/reference/workflow-syntax-for-github-actions

name: Rust Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        rust-version: stable
    - name: Test all rust libraries
      run: |
        echo "Searching for Rust project subfolders..."
        for dir in $(find . -type f -name 'Cargo.toml' -exec dirname {} \;); do
          if [ -f "$dir/Makefile" ]; then
            echo "Running make test in $dir"
            (cd "$dir" && make test)
          else
            echo "Skipping $dir (no Makefile)"
          fi
        done

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        rust-version: stable
    - name: Build
      run:  |
        echo "Searching for Rust project subfolders..."
        for dir in $(find . -type f -name 'Cargo.toml' -exec dirname {} \;); do
          if [ -f "$dir/Makefile" ]; then
            echo "Running make test in $dir"
            (cd "$dir" && make release)
          else
            echo "Skipping $dir (no Makefile)"
          fi
        done